CPU: 'xslx_data_source/CPU_data.xlsx'
MEMORY: 'xslx_data_source/MEMORY.xlsx'
NET: 'xslx_data_source/NET.xlsx'
LOAD_AVG: 'xslx_data_source/LOAD_avg.xlsx'
UTIL_DISK_CPU: 'xslx_data_source/DISK_cpu.xlsx'
DISK_QUEUE: 'xslx_data_source/DISK_q.xlsx'
DISK_AWG_RW: 'xslx_data_source/DISK_avg_rw.xlsx'
OUTPUT_DIR: 'result_graphs'